### ISSUE TITLE
psize_TE > 100 ?

### ISSUE THREAD

**Issue by aurelpetit** [DrosophilaGenomeEvolution/TrEMOLO#27] opened 2024-11-22 10:01 UTC
Hello !

I ran TrEMOLO on a genome assembly of A. thaliana, and in the TE_infos.bed I have a problem, some psize_TE have weird values. Here is an example :
start | end | TE\|ID | strand | TSD | pident | **psize_TE** | SIZE_TE | NEW_POS | FREQ | FREQ_WITH_CLIPPED | SV_SIZE | ID_TrEMOLO | TYPE
Chr2_RagTag | 6888229 | 6888230 | ATCOPIA32@ATCOPIA32\|sniffles.INS.2812 | - | ACCTCT | 95.946 | **9593.33** | 5771 | 6888229 | 9.67742 | 9.67742 | 13597 | TE_ID_OUTSIDER.92833.INS.84493 | INS

How is it possible ? 

Thank you very much in advance :)

Aurélien Petit

**Comment by M-D75** [comment] 2024-11-22 15:07
Hi,

It is possible that this error was fixed in the `fix_issue_23` branch. Someone had reported this issue to me (not in the Git issues), but I simply didn’t merge the fix into a new release.

If it is indeed the problem I’m thinking of, it is caused by the FASTA format of your TE database (`DB_TE`). I assume that the TE sequences are spread over multiple lines instead of being on a single line per TE. This bug is likely due to the script taking the first line of each TE sequence (which may be, for example, 80 base pairs per line) and comparing it to your inserted TE.

To apply the fix, you have two options: reformat your database or retrieve the version with the fix.

Using the command:

```bash
git clone https://github.com/DrosophilaGenomeEvolution/TrEMOLO.git -b fix_issue_23
```

Or from your existing repository:

```bash
git pull
git checkout fix_issue_23
```

Best,
M-D

**Closed** 2024-11-26 16:20 UTC
